### ISSUE TITLE
Dialog doesn't appear if navigation bar is hidden

### ISSUE THREAD

**Issue by tremby** [callahad/quick-accept-language-switcher#1]
I'm using Vimperator and usually hide the navigation toolbar. I've put the accept language switcher icon on the same toolbar as the tabs. Clicking it just highlights it but shows no dialog if the navigation bar is hidden. If I re-enable the navigation bar, clicking the button seems to work OK.

I suspect you have some logic tied specifically to the navigation bar and haven't taken into account that the icon may have been moved to a different toolbar.

**Comment by callahad** [comment]
I suspect this is an upstream bug with Firefox's WebExtension APIs, since this add-on doesn't define any of its own showing or hiding logic.

I'll file a corresponding ticket in Bugzilla when I wake up tomorrow. Thank you for the report!

**Comment by tremby** [comment]
Touché! :)

**Comment by callahad** [comment]
I've filed this at [Bug 1296377](https://bugzilla.mozilla.org/show_bug.cgi?id=1296377)

As a workaround, you can get the same effect with `:set! intl.accept_languages="en, fr"`, etc.

**Comment by callahad** [comment]
The upstream bug has been marked as WONTFIX, since hiding the navigation bar is not a supported configuration. Closing this in turn.

It'd probably be straightforward to build a Vimperator plugin to expose the above setting via a shorter command, like `:lang` or similar. There are a bunch of example plugins at http://vimpr.github.io/plugins-en.html

Good luck. :)

**Comment by tremby** [comment]
Yikes. Sorry to hear that.

Thanks for pointing out the workarounds.
